variables:
  DB_NAME: "ceatus_nahl"
  CLIENT_NAME: "ceatus"
  PROJECT_NAME: "nahl"
  GIT_STRATEGY: none
stages:
- deploy

deploy_develop:
  stage: deploy
  script:
  - sudo -u www-data reporobot --repository-url=$CI_REPOSITORY_URL --branch=develop --client=$CLIENT_NAME --project=$PROJECT_NAME --database=$DB_NAME --import-database --backup-database --keep-uploads
  only:
  - develop
  tags:
  - develop

deploy_master:
  stage: deploy
  script:
  - sudo -u www-data reporobot --repository-url=$CI_REPOSITORY_URL --branch=master --client=$CLIENT_NAME --project=$PROJECT_NAME --database=$DB_NAME --import-database --backup-database --keep-uploads
  only:
  - master
  tags:
  - master
  
deploy_other:
  stage: deploy
  script:
  - sudo -u www-data reporobot --repository-url=$CI_REPOSITORY_URL --branch=$CI_COMMIT_REF_NAME --client=$CLIENT_NAME --project=$PROJECT_NAME --database=$DB_NAME --import-database
  except:
  - develop
  - master
  tags:
  - other
